<div id="footer">
    <p>
        &copy; 2013 NEUMONT UNIVERSITY. ALL RIGHTS RESERVED <br>
        SOUTH JORDAN CAMPUS - 10701 SOUTH RIVER FRONT PARKWAY, SUITE 300, SOUTH JORDAN, UTAH 84095
    </p>
</div>